<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::whereNotNull('parent_id')->get()->keyBy('slug');

        $products = [
            // Grocery - Rice & Grains
            [
                'name' => 'Premium Miniket Rice 5kg',
                'slug' => 'premium-miniket-rice-5kg',
                'description' => 'High-quality Miniket rice, perfect for daily cooking. Long-grained, aromatic, and thoroughly cleaned. Packed in a resealable bag for freshness.',
                'short_description' => 'Premium quality Miniket rice, 5kg pack',
                'price' => 650,
                'compare_price' => 750,
                'sku' => 'GRO-RICE-001',
                'category_slug' => 'rice-grains',
                'brand' => 'FreshFarm',
                'unit' => 'kg',
                'weight' => 5.00,
                'stock_quantity' => 100,
                'is_featured' => true,
                'is_trending' => true,
                'rating' => 4.5,
                'review_count' => 128,
                'sold_count' => 1520,
                'image' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
            ],
            [
                'name' => 'Organic Red Lentil (Masoor Dal) 1kg',
                'slug' => 'organic-red-lentil-1kg',
                'description' => 'Premium organic red lentils, sorted and cleaned. Rich in protein and fiber. Perfect for daily dal preparation.',
                'short_description' => 'Organic red lentils, 1kg pack',
                'price' => 180,
                'compare_price' => 220,
                'sku' => 'GRO-DAL-001',
                'category_slug' => 'rice-grains',
                'brand' => 'OrganicValley',
                'unit' => 'kg',
                'weight' => 1.00,
                'stock_quantity' => 80,
                'is_featured' => true,
                'rating' => 4.3,
                'review_count' => 89,
                'sold_count' => 980,
                'image' => 'https://images.unsplash.com/photo-1585996746637-3d7f0c02e5e3?w=400',
            ],
            // Grocery - Oil & Ghee
            [
                'name' => 'Pure Mustard Oil 1L',
                'slug' => 'pure-mustard-oil-1l',
                'description' => 'Cold-pressed pure mustard oil from premium seeds. Natural, unrefined, and rich in flavor. Ideal for cooking and frying.',
                'short_description' => 'Cold-pressed pure mustard oil, 1 liter',
                'price' => 280,
                'compare_price' => 320,
                'sku' => 'GRO-OIL-001',
                'category_slug' => 'oil-ghee',
                'brand' => 'PurePress',
                'unit' => 'L',
                'weight' => 1.00,
                'stock_quantity' => 60,
                'is_trending' => true,
                'rating' => 4.4,
                'review_count' => 156,
                'sold_count' => 2100,
                'image' => 'https://images.unsplash.com/photo-1611931962790-971e9b4e15b7?w=400',
            ],
            // Grocery - Spices
            [
                'name' => 'Premium Turmeric Powder 200g',
                'slug' => 'premium-turmeric-powder-200g',
                'description' => 'Pure ground turmeric from certified organic farms. Bright yellow color, rich curcumin content. No artificial colors or additives.',
                'short_description' => 'Organic turmeric powder, 200g pack',
                'price' => 95,
                'compare_price' => null,
                'sku' => 'GRO-SPC-001',
                'category_slug' => 'spices',
                'brand' => 'SpiceKing',
                'unit' => 'g',
                'weight' => 0.20,
                'stock_quantity' => 120,
                'rating' => 4.6,
                'review_count' => 234,
                'sold_count' => 3400,
                'image' => 'https://images.unsplash.com/photo-1596040033229-98257c9a9c6d?w=400',
            ],
            // Grocery - Beverages
            [
                'name' => 'Premium Green Tea 100 Bags',
                'slug' => 'premium-green-tea-100-bags',
                'description' => 'Finest green tea leaves sourced from high-altitude gardens. Rich in antioxidants. 100 individually wrapped tea bags.',
                'short_description' => 'Premium green tea, 100 bags pack',
                'price' => 450,
                'compare_price' => 550,
                'sku' => 'GRO-BEV-001',
                'category_slug' => 'beverages',
                'brand' => 'TeaGarden',
                'unit' => 'pack',
                'weight' => 0.30,
                'stock_quantity' => 90,
                'is_featured' => true,
                'rating' => 4.2,
                'review_count' => 67,
                'sold_count' => 890,
                'image' => 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400',
            ],
            // Grocery - Snacks
            [
                'name' => 'Crunchy Potato Chips (Family Pack) 200g',
                'slug' => 'crunchy-potato-chips-200g',
                'description' => 'Lightly salted crispy potato chips made from premium potatoes. Perfect for snacking. Family-sized pack.',
                'short_description' => 'Crispy salted potato chips, 200g',
                'price' => 120,
                'compare_price' => 150,
                'sku' => 'GRO-SNK-001',
                'category_slug' => 'snacks',
                'brand' => 'CrunchBites',
                'unit' => 'g',
                'weight' => 0.20,
                'stock_quantity' => 200,
                'is_trending' => true,
                'rating' => 4.0,
                'review_count' => 45,
                'sold_count' => 560,
                'image' => 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
            ],
            // Electronics - Smartphones
            [
                'name' => 'SmartPhone Pro X 128GB',
                'slug' => 'smartphone-pro-x-128gb',
                'description' => 'Latest flagship smartphone with 6.7" AMOLED display, 108MP camera, 5000mAh battery, and 128GB storage. 5G ready.',
                'short_description' => 'Flagship smartphone, 128GB, 5G',
                'price' => 45999,
                'compare_price' => 52999,
                'sku' => 'ELEC-PHN-001',
                'category_slug' => 'smartphones',
                'brand' => 'TechPro',
                'unit' => 'piece',
                'weight' => 0.25,
                'stock_quantity' => 25,
                'is_featured' => true,
                'is_trending' => true,
                'rating' => 4.7,
                'review_count' => 312,
                'sold_count' => 1200,
                'image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400',
            ],
            [
                'name' => 'Budget SmartPhone Y5 64GB',
                'slug' => 'budget-smartphone-y5-64gb',
                'description' => 'Affordable smartphone with 6.5" display, 48MP camera, 4000mAh battery, and 64GB storage. Perfect for everyday use.',
                'short_description' => 'Budget smartphone, 64GB, dual SIM',
                'price' => 15999,
                'compare_price' => 18999,
                'sku' => 'ELEC-PHN-002',
                'category_slug' => 'smartphones',
                'brand' => 'TechPro',
                'unit' => 'piece',
                'weight' => 0.22,
                'stock_quantity' => 50,
                'rating' => 4.1,
                'review_count' => 89,
                'sold_count' => 3400,
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
            ],
            // Electronics - Laptops
            [
                'name' => 'UltraBook Pro 15" 16GB RAM',
                'slug' => 'ultrabook-pro-15-16gb',
                'description' => 'Lightweight ultrabook with 15.6" FHD display, Intel i7 processor, 16GB RAM, 512GB SSD. Battery life up to 12 hours.',
                'short_description' => 'Ultrabook i7, 16GB RAM, 512GB SSD',
                'price' => 85999,
                'compare_price' => 95999,
                'sku' => 'ELEC-LAP-001',
                'category_slug' => 'laptops',
                'brand' => 'TechPro',
                'unit' => 'piece',
                'weight' => 1.80,
                'stock_quantity' => 15,
                'is_featured' => true,
                'rating' => 4.6,
                'review_count' => 78,
                'sold_count' => 450,
                'image' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
            ],
            // Electronics - Headphones
            [
                'name' => 'Wireless Noise-Cancelling Headphones',
                'slug' => 'wireless-noise-cancelling-headphones',
                'description' => 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and premium sound quality.',
                'short_description' => 'ANC wireless headphones, 30hr battery',
                'price' => 5499,
                'compare_price' => 6999,
                'sku' => 'ELEC-AUD-001',
                'category_slug' => 'headphones',
                'brand' => 'SoundMax',
                'unit' => 'piece',
                'weight' => 0.35,
                'stock_quantity' => 40,
                'is_trending' => true,
                'rating' => 4.5,
                'review_count' => 201,
                'sold_count' => 2800,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
            ],
            // Electronics - Accessories
            [
                'name' => 'Fast Charger 65W USB-C',
                'slug' => 'fast-charger-65w-usb-c',
                'description' => 'GaN fast charger with 65W output, compatible with laptops, tablets, and smartphones. Compact design.',
                'short_description' => '65W GaN fast charger USB-C',
                'price' => 1299,
                'compare_price' => 1699,
                'sku' => 'ELEC-ACC-001',
                'category_slug' => 'accessories',
                'brand' => 'ChargePro',
                'unit' => 'piece',
                'weight' => 0.12,
                'stock_quantity' => 100,
                'rating' => 4.3,
                'review_count' => 445,
                'sold_count' => 5600,
                'image' => 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400',
            ],
            // Fashion - Men's Clothing
            [
                'name' => 'Classic Fit Cotton Formal Shirt',
                'slug' => 'classic-fit-cotton-formal-shirt',
                'description' => 'Premium 100% cotton formal shirt with classic fit. Wrinkle-resistant fabric. Available in multiple colors. Perfect for office wear.',
                'short_description' => 'Premium cotton formal shirt',
                'price' => 1899,
                'compare_price' => 2599,
                'sku' => 'FASH-MEN-001',
                'category_slug' => 'mens-clothing',
                'brand' => 'ElegantWear',
                'unit' => 'piece',
                'weight' => 0.30,
                'stock_quantity' => 75,
                'is_featured' => true,
                'rating' => 4.4,
                'review_count' => 167,
                'sold_count' => 1900,
                'image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400',
            ],
            // Fashion - Women's Clothing
            [
                'name' => 'Elegant Floral Maxi Dress',
                'slug' => 'elegant-floral-maxi-dress',
                'description' => 'Beautiful floral print maxi dress in soft viscose fabric. Features a flattering A-line silhouette with adjustable waist tie.',
                'short_description' => 'Floral print maxi dress, A-line',
                'price' => 2499,
                'compare_price' => 3299,
                'sku' => 'FASH-WMN-001',
                'category_slug' => 'womens-clothing',
                'brand' => 'ElegantWear',
                'unit' => 'piece',
                'weight' => 0.35,
                'stock_quantity' => 45,
                'is_trending' => true,
                'rating' => 4.6,
                'review_count' => 98,
                'sold_count' => 750,
                'image' => 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
            ],
            // Fashion - Footwear
            [
                'name' => 'Running Sneakers Air Max',
                'slug' => 'running-sneakers-air-max',
                'description' => 'Lightweight running sneakers with responsive cushioning and breathable mesh upper. Suitable for running and casual wear.',
                'short_description' => 'Lightweight running sneakers',
                'price' => 4499,
                'compare_price' => 5999,
                'sku' => 'FASH-FTW-001',
                'category_slug' => 'footwear',
                'brand' => 'SportFlex',
                'unit' => 'pair',
                'weight' => 0.60,
                'stock_quantity' => 60,
                'is_featured' => true,
                'rating' => 4.3,
                'review_count' => 234,
                'sold_count' => 3200,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
            ],
            // Household - Cleaning Supplies
            [
                'name' => 'Multi-Surface Cleaner 500ml',
                'slug' => 'multi-surface-cleaner-500ml',
                'description' => 'Powerful multi-surface cleaner that cuts through grease and grime. Safe for all washable surfaces. Lemon fresh scent.',
                'short_description' => 'Multi-surface cleaner, lemon scent',
                'price' => 199,
                'compare_price' => 249,
                'sku' => 'HHD-CLN-001',
                'category_slug' => 'cleaning-supplies',
                'brand' => 'CleanHome',
                'unit' => 'ml',
                'weight' => 0.50,
                'stock_quantity' => 150,
                'rating' => 4.2,
                'review_count' => 345,
                'sold_count' => 4500,
                'image' => 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=400',
            ],
            // Household - Kitchenware
            [
                'name' => 'Non-Stick Frying Pan 28cm',
                'slug' => 'non-stick-frying-pan-28cm',
                'description' => 'Premium non-stick frying pan with 3-layer coating. Suitable for all stovetops including induction. Ergonomic handle.',
                'short_description' => 'Non-stick frying pan, 28cm',
                'price' => 1599,
                'compare_price' => 1999,
                'sku' => 'HHD-KIT-001',
                'category_slug' => 'kitchenware',
                'brand' => 'CookMaster',
                'unit' => 'piece',
                'weight' => 1.10,
                'stock_quantity' => 35,
                'is_featured' => true,
                'rating' => 4.5,
                'review_count' => 189,
                'sold_count' => 2100,
                'image' => 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
            ],
            // Daily Essentials - Personal Care
            [
                'name' => 'Moisturizing Body Lotion 400ml',
                'slug' => 'moisturizing-body-lotion-400ml',
                'description' => 'Deeply moisturizing body lotion with natural shea butter and vitamin E. Non-greasy formula for all skin types.',
                'short_description' => 'Moisturizing body lotion, 400ml',
                'price' => 549,
                'compare_price' => 699,
                'sku' => 'DALY-PCR-001',
                'category_slug' => 'personal-care',
                'brand' => 'GlowUp',
                'unit' => 'ml',
                'weight' => 0.40,
                'stock_quantity' => 85,
                'is_trending' => true,
                'rating' => 4.3,
                'review_count' => 276,
                'sold_count' => 3800,
                'image' => 'https://images.unsplash.com/photo-1611931962790-971e9b4e15b7?w=400',
            ],
        ];

        foreach ($products as $productData) {
            $categorySlug = $productData['category_slug'];
            $image = $productData['image'];
            unset($productData['category_slug'], $productData['image']);

            $category = $categories->get($categorySlug);
            if (! $category) {
                continue;
            }

            $productData['category_id'] = $category->id;
            $product = Product::create($productData);

            ProductImage::create([
                'product_id' => $product->id,
                'image' => $image,
                'is_primary' => true,
                'sort_order' => 0,
            ]);
        }
    }
}
